version: '3.1'
services:
  stats-server:
    build: explore-stats/explore-stats-service
    image: explore-stats-service
    container_name: explore-stats-service
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/explorestats
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  stats-db:
    image: postgres:14-alpine
    container_name: explore-stats-db
    ports:
      - "6543:5432"
    environment:
      - POSTGRES_DB=explorestats
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root


